### PR TITLE
Create Discord redirect page 

### PR DESCRIPTION
**Pull request by Nathanwoodburn**
Add redirect file to fix vanity discord link getting deleted.

### CODE REVIEW

**Comment by pinheadmz** [comment]
Okay, not bad -- should we change the link on the other pages as well?
/index.html  also another one in /community/index.html

**Comment by Nathanwoodburn** [comment]
That would be good. However I would suggest pointing those sites to this page. That way if we ever change the link we only need to change the 1 spot.

**Comment by pinheadmz** [comment]
good idea, wanna dd that to this PR?

**Comment by Nathanwoodburn** [comment]
Yep will do

**Comment by Nathanwoodburn** [comment]
I've changed all the links I found. If you find any more let me know.

**Pull request merged**
