### PR TITLE
index: add link to Bob

### PR DESCRIPTION
**Pull request by pinheadmz**
Screen Shot 2021-01-13 at 11 58 32 AM

### CODE REVIEW

**Comment by jacobjonz** [comment]
I believe it's appropriate to have Bob linked directly on Handshake.org given Bob is currently the only GUI that allows users to hold their HNS assets with their own private keys. This will help new users to set themselves up in the Handshake space in line with the overall Handshake spirit of decentralisation.

**Comment by newb** [comment]
Agree with jacobjonz on this. +1

**Comment by brandondees** [comment]
Might be ideal to start denoting who is behind each tool/resource up front, just as sort of a full transparency thing and an early clue about how this is a community ecosystem with no central control.

e.g. "bob wallet by kyokan"

**Comment by faltrum** [comment]
I'm agree Jacobjonz and Brandondees. +1 +1

**Comment by pinheadmz** [comment]
Ok this is enough support for me to merge. If anyone objects in the future they can open a new PR.

@brandondees I hear you about denoting Kyokan. I prefer not to do this now for a few loose reasons, and we can address it again in a future issue or PR:
- There are no brand names called out, sponsored, or otherwise endorsed on this page (yet)
- Internally, Bob is just hsd anyway which is a handshake-org repository
- Kyokan was commissioned by the founders to build Bob, in that sense it is already kinda handshake-org property
- It's fairly easy to discover who wrote the Bob UI by following the links provided

**Pull request merged**
