### PR TITLE
Remove "experimental" from front page index.html

### PR DESCRIPTION
**Pull request by walletdomain**
Propose removing the word "experimental" in one location.

### CODE REVIEW

**Comment by pinheadmz** [comment]
NACK.

Handshake is an experiment. There is no reason to convey over-confidence in the protocol or technology. [Even Bitcoin is still an experiment](https://github.com/bitcoin/bitcoin#what-is-bitcoin). Bitcoin Core release versions always start with a `0` because even in the opinion of the most dedicated of core developers, [it is still in "beta".](https://bitcoin.stackexchange.com/a/95281/3667)

Handshake is barely a year old, has less than 200 network nodes and only a handful of mining pools. The hashrate is relatively very low. In the next 12 months we could see hard forks, soft forks, alternative implementations, completely new use cases outside of DNS -- we could even see a total consensus failure, splintering of the community or unrecoverable attack on the network.

`hsd` is the first (alt)cryptocurrency full-node written entirely in nodeJS. It has a relatively tiny community of contributing developers and employs [brand-new cryptographic schemes](http://fc20.ifca.ai/preproceedings/54.pdf) and even uses a [brand-new data structure.](https://github.com/handshake-org/urkel#design)

The airdrop format and currency distribution has never been attempted before. The auction rules/game play construction has never been attempted before. The governance model (no lingering foundation or funding) is either extremely rare (to my knowledge) or has not actually ever been attempted in the last nine-ten years.

Everyone who uses Handshake needs to know it can be extremely dangerous, volatile, unsafe, unpredictable, unreliable.

I can not think of a better single word to describe it than "experiment".

I'm curious @tikaboo if you'd like to expand on your motivations for this pull request? Otherwise I see no reason to remove this word.

**Comment by walletdomain** [comment]
Thanks for the feedback. The proposal was based on the notion that Handshake is in a production state now. All of the adjectives that you used to describe it's potential can apply to something in an experimental state or not. The fact that the protocol and chain uses cutting edge technology that has not been used before still does not leave it in a state of experimental. I think it is a marketing issue. In order to grow it beyond it's current state (whatever that state is defined as), we need integrations. I think the perception of the experimental state of it is holding back adoption and integration possibilities. Tesla would never market their vehicle as "an experimental car" even though it maintains about the same qualities of state that you mentioned handshake still has. I don't think you would be misleading integrators by removing the word experimental. You still have a great complete narrative and explanation of what it is and what it isn't. Mainnet is live and in production now though, so if we want others to adopt, I think the change of that one word would help. Even changing it to something like "pioneering" or "revolutionary" would help.

**Comment by johnnywu-namebase** [comment]
Great points on both fronts! I definitely like "pioneering" or "revolutionary" but I don't think those words fit with the vibe of the rest of the website — I liked Scott's (the other one haha) proposal that's a pretty good middle ground: "emerging"

**Comment by smcki012** [comment]
NACK, Handshake is an experiment. This is an unnecessary point of friction given the social contract purposely tries to eliminate the site being used as static documentation of the chain's ethos. Important we honor that.

**Comment by dnsguru** [comment]
NACK.   Don't dilute the important word and its meaning to this project.

Labelling this as an experiment level sets expectations while the usability and other aspects of the project evolve.

The rationale that was provided in the chat discussion that prompted this pr was around a circumstance of the term "experiment" or "experimental" eroding the institutional confidence in this project by a certificate authority.  

While this one text change might remove calling immediate attention to the state of the project, other aspects of the evolutionary phase this is in are the actual obstacles.  The inability to look up a string owner point of contact (by design) or address resolvability or other elements of this project that create friction to adoption by existing providers, and altering the costume on that will not result in the desired outcome.

It is better to be authentic with what this project is and is not, and experiment is where it is right now. 

The suggestion about emerging being ADDED is ok, because there is a growing interest and community, but removing the term experimental is not ok.

**Comment by walletdomain** [comment]
Sorry. Did not mean to cause any friction with the suggestion. I can close the request.

**Comment by offordscott** [comment]
I vote for `emerging`

**Comment by rafaelcastrocouto** [comment]
Although I agree that we should be honest about the expectations and that the word 'experimental' doesn't really hurt that much, I gotta point out that you will not find this word in the bitcoin.org website. At this time they are using the logo "Bitcoin is an innovative payment network and a new kind of money." 

I think we could replace 'experimental' with 'innovative' or 'emerging' and move the term to the repository description just like they did basically for marketing reasons. Or not, it's not a huge deal (I don't mean to raise more friction, just leaving my late opinion).

**Comment by pinheadmz** [comment]
>  I gotta point out that you will not find this word in the bitcoin.org website. 

https://bitcoin.org/en/you-need-to-know#experimental

**Pull request closed without merging**
